name: Lint and Scan Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform_lint_scan:
    name: Terraform Lint and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.1

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Run TFLint
        run: tflint --init && tflint -f compact

      - name: Run tfsec (security scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .
